# Generated by Django 5.2.10 on 2026-01-08 22:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='Ключевое слово/тема')),
                ('category', models.CharField(choices=[('work', 'Работа'), ('study', 'Учёба'), ('family', 'Семья'), ('friends', 'Друзья'), ('health', 'Здоровье'), ('hobby', 'Хобби'), ('finance', 'Финансы'), ('rest', 'Отдых'), ('sport', 'Спорт'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Ключевое слово',
                'verbose_name_plural': 'Ключевые слова',
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Опишите свой день, мысли, события...', verbose_name='Текст записи')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('mood_score', models.FloatField(blank=True, help_text='От -1 (очень негативное) до 1 (очень позитивное)', null=True, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Оценка настроения (авто)')),
                ('user_mood_tag', models.CharField(choices=[('excellent', 'Отличное'), ('good', 'Хорошее'), ('neutral', 'Нейтральное'), ('bad', 'Плохое'), ('terrible', 'Ужасное')], default='neutral', max_length=20, verbose_name='Метка настроения')),
                ('word_count', models.IntegerField(default=0, verbose_name='Количество слов')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Дневниковая запись',
                'verbose_name_plural': 'Дневниковые записи',
                'ordering': ['-date_created'],
                'indexes': [models.Index(fields=['user', 'date_created'], name='diary_diary_user_id_2e506c_idx')],
            },
        ),
        migrations.CreateModel(
            name='MoodCorrelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_score', models.FloatField(help_text='-1: сильная негативная, 0: нет связи, 1: сильная позитивная', validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Коэффициент корреляции')),
                ('occurrence_count', models.IntegerField(default=0, verbose_name='Количество упоминаний')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlations', to='diary.extractedkeyword', verbose_name='Ключевое слово')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_correlations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корреляция настроения',
                'verbose_name_plural': 'Корреляции настроений',
                'ordering': ['user', '-correlation_score'],
                'unique_together': {('user', 'keyword')},
            },
        ),
    ]
