# Generated by Django 5.2.10 on 2026-01-11 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='user_mood_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценка пользователя'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='mood_score',
            field=models.FloatField(blank=True, help_text='От -10 (очень негативное) до 10 (очень позитивное)', null=True, validators=[django.core.validators.MinValueValidator(-10.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Оценка настроения (авто)'),
        ),
        migrations.AlterField(
            model_name='moodcorrelation',
            name='correlation_score',
            field=models.FloatField(help_text='-10: сильная негативная, 0: нет связи, 10: сильная позитивная', validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(10)], verbose_name='Коэффициент корреляции'),
        ),
    ]
